#
# Copyright (c) 2025 UsefulWorks Ltd.
#

url: "https://usefulworks.uk" # the base hostname & protocol for your site, e.g. http://example.com
email: "hello@usefulworks.uk"
baseurl: "" # the subpath of your site, e.g. /blog
title: "UsefulWorks" # the name of your site, e.g. ACME Corp.

foobar: "suprise!"
